## Sample of getStructuringElement()

指定サイズのカーネルを作成する

### Patameter
- shape
    - cv2.MORPH_RECT - すべて1
    - cv2.MORPH_ELLIPSE - 楕円形
    - cv2.MORPH_CROSS - 十字型
- ksize
    - カーネルのサイズ
- anchor
    - MORPH_CROSSのみ影響あり
    - 十字の中心の座標を表す
    - (-1, -1) : 特別な座標で、カーネルの中心を示す

[opencv docs](https://docs.opencv.org/4.4.0/d4/d86/group__imgproc__filter.html#gac342a1bb6eabf6f55c803b09268e36dc)  
[参考](https://geekn-nerd.blogspot.com/2012/03/3-opencv-for-android_20.html)

In [1]:
import cv2

import numpy as np
from matplotlib import pyplot as plt

In [11]:
size = (5, 5)
anchor = (1, 1)

kernel=cv2.getStructuringElement(cv2.MORPH_CROSS, size, anchor)

print(kernel)

[[0 1 0 0 0]
 [1 1 1 1 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]]
